// <auto-generated />
using BokRegister.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BokRegister.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240902113935_Seeded Books")]
    partial class SeededBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BokRegister.Api.Models.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Isbn");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Isbn = "9780061120084",
                            Author = "Harper Lee",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Isbn = "9780451524935",
                            Author = "George Orwell",
                            Title = "1984"
                        },
                        new
                        {
                            Isbn = "9780743273565",
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Isbn = "9781503290563",
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Isbn = "9780316769488",
                            Author = "J.D. Salinger",
                            Title = "The Catcher in the Rye"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
